In [35]:
import re, ast
import pandas as pd

with open("results/raw_shap_nightrun.md", "r", encoding="utf-8") as f:
    night_run = f.read()

In [24]:
all_blocks = night_run.split("Variable:")
all_blocks = [b.strip() for b in all_blocks if b.strip()]

all_blocks = all_blocks[1:]

In [25]:
all_blocks

["tradeflow_baci\\nRF basic: {'model_name': 'RandomForest_tradeflow_baci', 'n_train': 3640, 'n_test': 910, 'rmse': 2.1969234699638394, 'mae': 1.5707153376721754, 'r2': 0.48236444266050016, 'shap importance (grouped)': {'exporter_FE': np.float64(1.0825656624986466), 'importer_FE': np.float64(0.5285056627256377), 'other': {'contig': np.float64(0.3804110992038566), 'comlang_off': np.float64(0.10057214821250529), 'comlang_ethno': np.float64(0.062156051780437885), 'log_gdp_o': np.float64(0.7346613360759036), 'log_gdp_d': np.float64(0.4353649468565382), 'log_distw': np.float64(0.5444576907836274)}}}\\nRF full: {'model_name': 'RandomForest_tradeflow_baci', 'n_train': 3640, 'n_test': 910, 'rmse': 2.347837909776248, 'mae': 1.7718221272556067, 'r2': 0.40880539026556406, 'shap importance (grouped)': {'exporter_FE': np.float64(0.5906058946141746), 'importer_FE': np.float64(0.4119161509340978), 'other': {'contig': np.float64(0.3599775106497096), 'comlang_off': np.float64(0.07959070571625103), 'comlang_ethno': np.float64(0.029338673634806935), 'disorder_Demonstrations': np.float64(0.08365424972406632), 'disorder_Political violence': np.float64(0.040316828733368684), 'disorder_Political violence; Demonstrations': np.float64(0.010030499306570476), 'disorder_Strategic developments': np.float64(0.02859918034779883), 'event_Battles': np.float64(0.05014945970964223), 'event_Explosions/Remote violence': np.float64(0.01823149138160111), 'event_Protests': np.float64(0.05498979870474672), 'event_Riots': np.float64(0.0486678508119306), 'event_Strategic developments': np.float64(0.023109159863245576), 'event_Violence against civilians': np.float64(0.03856787590539285), 'perpetrator_Civilians': np.float64(0.00044673327037338204), 'perpetrator_External/Other forces': np.float64(0.02821751146852231), 'perpetrator_Identity militia': np.float64(0.12026872885354765), 'perpetrator_Political militia': np.float64(0.06672550868075666), 'perpetrator_Protesters': np.float64(0.0514471682778462), 'perpetrator_Rebel group': np.float64(0.025129557223959362), 'perpetrator_Rioters': np.float64(0.041315544398397276), 'perpetrator_State forces': np.float64(0.0441538348798147), 'target_Civilians': np.float64(0.03281356046798098), 'target_External/Other forces': np.float64(0.024854912839709545), 'target_Identity militia': np.float64(0.051437770459417644), 'target_Political militia': np.float64(0.02732198626394697), 'target_Protesters': np.float64(0.020011073137134038), 'target_Rebel group': np.float64(0.021320507671125657), 'target_Rioters': np.float64(0.02074912066401582), 'target_State forces': np.float64(0.0314369475160232), 'log_gdp_o': np.float64(0.5504997108091838), 'log_gdp_d': np.float64(0.38088317542645783), 'log_distw': np.float64(0.5177760600922029)}}}\\nMLP basic: {'model_name': 'MLP_tradeflow_baci', 'n_train': 3640, 'n_test': 910, 'rmse': 2.1794839386429676, 'mae': 1.6349067317737656, 'r2': 0.4905499725380611, 'shap importance (grouped)': {'exporter_FE': np.float64(1.352158674525605), 'importer_FE': np.float64(0.6232996500466217), 'other': {'contig': np.float64(0.38825202114039775), 'comlang_off': np.float64(0.07162775336597887), 'comlang_ethno': np.float64(0.1111726347931451), 'log_gdp_o': np.float64(0.38956910821478136), 'log_gdp_d': np.float64(0.8268301277848659), 'log_distw': np.float64(0.39755587900955086)}}}\\nMLP full: {'model_name': 'MLP_tradeflow_baci', 'n_train': 3640, 'n_test': 910, 'rmse': 12.63247503299985, 'mae': 5.371200332441091, 'r2': -16.11477292202991, 'shap importance (grouped)': {'exporter_FE': np.float64(1.3345178550050958), 'importer_FE': np.float64(0.9271528433995019), 'other': {'contig': np.float64(0.2862672430161284), 'comlang_off': np.float64(0.38411440316167483), 'comlang_ethno': np.float64(0.13950536072272404), 'disorder_Demonstrations': np.float64(0.0229632477764624), 'disorder_Political violence': np.float64(0.01528097608958887), 'disorder_Political violence; Demonstrations': np.float64(0.07428361243986403), 'disorder_Strategic developments': np.float64(0.02449734203929101), 'event_Battles': np.float64(0.04159497092499571), 'event_Explosions/Remote violence': np.float64(0.05934916225044188), 'event_Protests': np.float64(0.10236306025784724), 'event_Riots': np.float64(0.4813270684228174), 'event_Strategic developments': np.float64(0.0916949425665375), 'event_Violence against civilians': np.float64(0.3565199597346686), 'perpetrator_Civilians': np.float64(0.003521311855141929), 'perpetrator_External/Other forces': np.float64(0.024644423485195792), 'perpetrator_Identity militia': np.float64(0.09269949148524238), 'perpetrator_Political militia': np.float64(0.03400025820605143), 'perpetrator_Protesters': np.float64(0.022603330766232638), 'perpetrator_Rebel group': np.float64(0.1154276248290295), 'perpetrator_Rioters': np.float64(0.17641908100672576), 'perpetrator_State forces': np.float64(0.06915530166810846), 'target_Civilians': np.float64(0.030780461896741464), 'target_External/Other forces': np.float64(0.12170712521941533), 'target_Identity militia': np.float64(0.04758672807441111), 'target_Political militia': np.float64(0.13083425775703458), 'target_Protesters': np.float64(0.039504928685164996), 'target_Rebel group': np.float64(0.047562790628982804), 'target_Rioters': np.float64(0.06700253125322035), 'target_State forces': np.float64(0.14867593337813742), 'log_gdp_o': np.float64(0.3918894381860678), 'log_gdp_d': np.float64(1.2152296003481982), 'log_distw': np.float64(0.381712405928879)}}}\\nXGB basic: {'model_name': 'XGBoost_tradeflow_baci', 'n_train': 3640, 'n_test': 910, 'rmse': 2.248696124591908, 'mae': 1.629405909482402, 'r2': 0.4576797925330913, 'shap importance (grouped)': {'exporter_FE': np.float32(1.1000466), 'importer_FE': np.float32(0.48996437), 'other': {'contig': np.float32(0.41711366), 'comlang_off': np.float32(0.058545556), 'comlang_ethno': np.float32(0.026004603), 'log_gdp_o': np.float32(0.8640532), 'log_gdp_d': np.float32(0.5674534), 'log_distw': np.float32(0.63089544)}}}\\nXGB full: {'model_name': 'XGBoost_tradeflow_baci', 'n_train': 3640, 'n_test': 910, 'rmse': 2.3778108685004953, 'mae': 1.74401574110632, 'r2': 0.39361442745670727, 'shap importance (grouped)': {'exporter_FE': np.float32(0.74835795), 'importer_FE': np.float32(0.5026265), 'other': {'contig': np.float32(0.4014124), 'comlang_off': np.float32(0.058334343), 'comlang_ethno': np.float32(0.023343883), 'disorder_Demonstrations': np.float32(0.06408133), 'disorder_Political violence': np.float32(0.055403486), 'disorder_Political violence; Demonstrations': np.float32(0.0132161), 'disorder_Strategic developments': np.float32(0.034522418), 'event_Battles': np.float32(0.05221999), 'event_Explosions/Remote violence': np.float32(0.02726426), 'event_Protests': np.float32(0.047266304), 'event_Riots': np.float32(0.043777935), 'event_Strategic developments': np.float32(0.0113256), 'event_Violence against civilians': np.float32(0.04372717), 'perpetrator_Civilians': np.float32(0.0004813217), 'perpetrator_External/Other forces': np.float32(0.022466943), 'perpetrator_Identity militia': np.float32(0.038238022), 'perpetrator_Political militia': np.float32(0.078285605), 'perpetrator_Protesters': np.float32(0.030691402), 'perpetrator_Rebel group': np.float32(0.037447818), 'perpetrator_Rioters': np.float32(0.024549231), 'perpetrator_State forces': np.float32(0.06975314), 'target_Civilians': np.float32(0.04290983), 'target_External/Other forces': np.float32(0.03655358), 'target_Identity militia': np.float32(0.027504481), 'target_Political militia': np.float32(0.064246655), 'target_Protesters': np.float32(0.008677454), 'target_Rebel group': np.float32(0.016945057), 'target_Rioters': np.float32(0.03125715), 'target_State forces': np.float32(0.044453338), 'log_gdp_o': np.float32(0.9764292), 'log_gdp_d': np.float32(0.5447524), 'log_distw': np.float32(0.6206511)}}}\\n\\n",
 "tradeflow_comtrade_o\\nRF basic: {'model_name': 'RandomForest_tradeflow_comtrade_o', 'n_train': 3640, 'n_test': 910, 'rmse': 1.9274115806045566, 'mae': 1.3952320006000458, 'r2': 0.47443790213118586, 'shap importance (grouped)': {'exporter_FE': np.float64(1.081209488774185), 'importer_FE': np.float64(0.3865783426255016), 'other': {'contig': np.float64(0.3985036825583303), 'comlang_off': np.float64(0.09060126993073386), 'comlang_ethno': np.float64(0.04946369303781195), 'log_gdp_o': np.float64(0.6412958518839729), 'log_gdp_d': np.float64(0.47797264112930804), 'log_distw': np.float64(0.5005014212324125)}}}\\nRF full: {'model_name': 'RandomForest_tradeflow_comtrade_o', 'n_train': 3640, 'n_test': 910, 'rmse': 2.10162738290778, 'mae': 1.6094738669845696, 'r2': 0.37513450128983883, 'shap importance (grouped)': {'exporter_FE': np.float64(0.595355158559791), 'importer_FE': np.float64(0.26028811849499905), 'other': {'contig': np.float64(0.37665022469104287), 'comlang_off': np.float64(0.0444530328281404), 'comlang_ethno': np.float64(0.0298750449821933), 'disorder_Demonstrations': np.float64(0.06176695250849021), 'disorder_Political violence': np.float64(0.08758406701838405), 'disorder_Political violence; Demonstrations': np.float64(0.018790540052670338), 'disorder_Strategic developments': np.float64(0.021049892217455624), 'event_Battles': np.float64(0.05692165324773686), 'event_Explosions/Remote violence': np.float64(0.02127365022943414), 'event_Protests': np.float64(0.08718278443897677), 'event_Riots': np.float64(0.053209248343179), 'event_Strategic developments': np.float64(0.02096436897445534), 'event_Violence against civilians': np.float64(0.051947069705544156), 'perpetrator_Civilians': np.float64(0.0013626181656173843), 'perpetrator_External/Other forces': np.float64(0.0146144497072394), 'perpetrator_Identity militia': np.float64(0.059996729101336535), 'perpetrator_Political militia': np.float64(0.08778111760122657), 'perpetrator_Protesters': np.float64(0.07270209898260596), 'perpetrator_Rebel group': np.float64(0.02205328383316557), 'perpetrator_Rioters': np.float64(0.06758083269293258), 'perpetrator_State forces': np.float64(0.02748367667371777), 'target_Civilians': np.float64(0.03963659397911242), 'target_External/Other forces': np.float64(0.008581984261504246), 'target_Identity militia': np.float64(0.03947284618636259), 'target_Political militia': np.float64(0.025282347038504908), 'target_Protesters': np.float64(0.02488565845844944), 'target_Rebel group': np.float64(0.017970391418175427), 'target_Rioters': np.float64(0.01995328324390897), 'target_State forces': np.float64(0.03507901415994977), 'log_gdp_o': np.float64(0.4252161286033871), 'log_gdp_d': np.float64(0.4514630116790537), 'log_distw': np.float64(0.4477654436738082)}}}\\nMLP basic: {'model_name': 'MLP_tradeflow_comtrade_o', 'n_train': 3640, 'n_test': 910, 'rmse': 2.001793119483314, 'mae': 1.3975732315846348, 'r2': 0.43309081459612253, 'shap importance (grouped)': {'exporter_FE': np.float64(2.241802434310602), 'importer_FE': np.float64(0.4729952510289044), 'other': {'contig': np.float64(0.3728609304699415), 'comlang_off': np.float64(0.04860449026604453), 'comlang_ethno': np.float64(0.04357694961725281), 'log_gdp_o': np.float64(0.8542764740965195), 'log_gdp_d': np.float64(0.5426027296142316), 'log_distw': np.float64(0.3789287185971294)}}}\\nMLP full: {'model_name': 'MLP_tradeflow_comtrade_o', 'n_train': 3640, 'n_test': 910, 'rmse': 10.883838024190176, 'mae': 4.52925496952788, 'r2': -15.758658421757278, 'shap importance (grouped)': {'exporter_FE': np.float64(2.3275705302042593), 'importer_FE': np.float64(0.44589685707186216), 'other': {'contig': np.float64(0.24133374490570159), 'comlang_off': np.float64(0.07068422519389195), 'comlang_ethno': np.float64(0.022734256746900924), 'disorder_Demonstrations': np.float64(0.09352036178823879), 'disorder_Political violence': np.float64(0.009908732410656575), 'disorder_Political violence; Demonstrations': np.float64(0.04451096468879876), 'disorder_Strategic developments': np.float64(0.005535928528274886), 'event_Battles': np.float64(0.025346040928975584), 'event_Explosions/Remote violence': np.float64(0.05567796908313837), 'event_Protests': np.float64(0.0007436083006696078), 'event_Riots': np.float64(0.09200421478115474), 'event_Strategic developments': np.float64(0.015164829095518428), 'event_Violence against civilians': np.float64(0.22607463107450573), 'perpetrator_Civilians': np.float64(0.003382730269347187), 'perpetrator_External/Other forces': np.float64(0.01816159358683779), 'perpetrator_Identity militia': np.float64(0.012369149306027902), 'perpetrator_Political militia': np.float64(0.051845415536328626), 'perpetrator_Protesters': np.float64(0.0026985547102685086), 'perpetrator_Rebel group': np.float64(0.02052672522013842), 'perpetrator_Rioters': np.float64(0.2894682928781346), 'perpetrator_State forces': np.float64(0.1965187747054352), 'target_Civilians': np.float64(0.1219931724460609), 'target_External/Other forces': np.float64(0.045002834401436716), 'target_Identity militia': np.float64(0.01740243822935439), 'target_Political militia': np.float64(0.020488660812050957), 'target_Protesters': np.float64(0.030104782806434603), 'target_Rebel group': np.float64(0.2690980134511543), 'target_Rioters': np.float64(0.04521675851690039), 'target_State forces': np.float64(0.12355172753448594), 'log_gdp_o': np.float64(0.9544069066642936), 'log_gdp_d': np.float64(0.4881640267747589), 'log_distw': np.float64(0.4252702479618518)}}}\\nXGB basic: {'model_name': 'XGBoost_tradeflow_comtrade_o', 'n_train': 3640, 'n_test': 910, 'rmse': 1.9344408713304964, 'mae': 1.4163469417326804, 'r2': 0.47059745056800184, 'shap importance (grouped)': {'exporter_FE': np.float32(1.1817156), 'importer_FE': np.float32(0.22783117), 'other': {'contig': np.float32(0.40132627), 'comlang_off': np.float32(0.08053067), 'comlang_ethno': np.float32(0.030084332), 'log_gdp_o': np.float32(0.77875936), 'log_gdp_d': np.float32(0.6588386), 'log_distw': np.float32(0.55740553)}}}\\nXGB full: {'model_name': 'XGBoost_tradeflow_comtrade_o', 'n_train': 3640, 'n_test': 910, 'rmse': 2.12434405605774, 'mae': 1.5439671882546238, 'r2': 0.3615530432448212, 'shap importance (grouped)': {'exporter_FE': np.float32(0.8619643), 'importer_FE': np.float32(0.24710253), 'other': {'contig': np.float32(0.41379368), 'comlang_off': np.float32(0.07149641), 'comlang_ethno': np.float32(0.02475908), 'disorder_Demonstrations': np.float32(0.060545627), 'disorder_Political violence': np.float32(0.09586512), 'disorder_Political violence; Demonstrations': np.float32(0.03434796), 'disorder_Strategic developments': np.float32(0.038690522), 'event_Battles': np.float32(0.06494036), 'event_Explosions/Remote violence': np.float32(0.045246348), 'event_Protests': np.float32(0.042555258), 'event_Riots': np.float32(0.04307002), 'event_Strategic developments': np.float32(0.007946613), 'event_Violence against civilians': np.float32(0.067730196), 'perpetrator_Civilians': np.float32(0.00022004919), 'perpetrator_External/Other forces': np.float32(0.030976782), 'perpetrator_Identity militia': np.float32(0.028595738), 'perpetrator_Political militia': np.float32(0.07944926), 'perpetrator_Protesters': np.float32(0.04271039), 'perpetrator_Rebel group': np.float32(0.025755553), 'perpetrator_Rioters': np.float32(0.04134899), 'perpetrator_State forces': np.float32(0.049897473), 'target_Civilians': np.float32(0.060781304), 'target_External/Other forces': np.float32(0.0102742), 'target_Identity militia': np.float32(0.028865162), 'target_Political militia': np.float32(0.017617337), 'target_Protesters': np.float32(0.019545443), 'target_Rebel group': np.float32(0.022783265), 'target_Rioters': np.float32(0.062054448), 'target_State forces': np.float32(0.07262119), 'log_gdp_o': np.float32(0.79269725), 'log_gdp_d': np.float32(0.6082367), 'log_distw': np.float32(0.5255255)}}}\\n\\n",

In [28]:
df_names = ["lag0", "lag1", "lag2"]

results = []

for idx, block in enumerate(all_blocks):

    df_id = df_names[idx // 6]  # ✅ now safe

    # convert escaped newlines FIRST
    block = block.replace("\\n", "\n")

    lines = block.split("\n")
    target = lines[0].strip()

    for line in lines[1:]:
        if ":" not in line:
            continue

        name, dict_str = line.split(":", 1)

        # clean numpy floats
        dict_str = re.sub(r"np\.float(32|64)\((.*?)\)", r"\2", dict_str)

        try:
            data = ast.literal_eval(dict_str)

            results.append({
                "target": target,
                "model_spec": name.strip(),
                "data_version": df_id,
                **data
            })

        except Exception as e:
            print("FAILED:", name)

In [34]:
results

[{'target': 'tradeflow_baci',
  'model_spec': 'RF basic',
  'data_version': 'lag0',
  'model_name': 'RandomForest_tradeflow_baci',
  'n_train': 3640,
  'n_test': 910,
  'rmse': 2.1969234699638394,
  'mae': 1.5707153376721754,
  'r2': 0.48236444266050016,
  'shap importance (grouped)': {'exporter_FE': 1.0825656624986466,
   'importer_FE': 0.5285056627256377,
   'other': {'contig': 0.3804110992038566,
    'comlang_off': 0.10057214821250529,
    'comlang_ethno': 0.062156051780437885,
    'log_gdp_o': 0.7346613360759036,
    'log_gdp_d': 0.4353649468565382,
    'log_distw': 0.5444576907836274}}},
 {'target': 'tradeflow_baci',
  'model_spec': 'RF full',
  'data_version': 'lag0',
  'model_name': 'RandomForest_tradeflow_baci',
  'n_train': 3640,
  'n_test': 910,
  'rmse': 2.347837909776248,
  'mae': 1.7718221272556067,
  'r2': 0.40880539026556406,
  'shap importance (grouped)': {'exporter_FE': 0.5906058946141746,
   'importer_FE': 0.4119161509340978,
   'other': {'contig': 0.3599775106497096,
    'comlang_off': 0.07959070571625103,
    'comlang_ethno': 0.029338673634806935,
    'disorder_Demonstrations': 0.08365424972406632,
    'disorder_Political violence': 0.040316828733368684,
    'disorder_Political violence; Demonstrations': 0.010030499306570476,
    'disorder_Strategic developments': 0.02859918034779883,
    'event_Battles': 0.05014945970964223,
    'event_Explosions/Remote violence': 0.01823149138160111,
    'event_Protests': 0.05498979870474672,
    'event_Riots': 0.0486678508119306,
    'event_Strategic developments': 0.023109159863245576,
    'event_Violence against civilians': 0.03856787590539285,
    'perpetrator_Civilians': 0.00044673327037338204,
    'perpetrator_External/Other forces': 0.02821751146852231,
    'perpetrator_Identity militia': 0.12026872885354765,
    'perpetrator_Political militia': 0.06672550868075666,
    'perpetrator_Protesters': 0.0514471682778462,
    'perpetrator_Rebel group': 0.025129557223959362,
    'perpetrator_Rioters': 0.041315544398397276,
    'perpetrator_State forces': 0.0441538348798147,
    'target_Civilians': 0.03281356046798098,
    'target_External/Other forces': 0.024854912839709545,
    'target_Identity militia': 0.051437770459417644,
    'target_Political militia': 0.02732198626394697,
    'target_Protesters': 0.020011073137134038,
    'target_Rebel group': 0.021320507671125657,
    'target_Rioters': 0.02074912066401582,
    'target_State forces': 0.0314369475160232,
    'log_gdp_o': 0.5504997108091838,
    'log_gdp_d': 0.38088317542645783,
    'log_distw': 0.5177760600922029}}},
 {'target': 'tradeflow_baci',
  'model_spec': 'MLP basic',
  'data_version': 'lag0',
  'model_name': 'MLP_tradeflow_baci',
  'n_train': 3640,
  'n_test': 910,
  'rmse': 2.1794839386429676,
  'mae': 1.6349067317737656,
  'r2': 0.4905499725380611,
  'shap importance (grouped)': {'exporter_FE': 1.352158674525605,
   'importer_FE': 0.6232996500466217,
   'other': {'contig': 0.38825202114039775,
    'comlang_off': 0.07162775336597887,
    'comlang_ethno': 0.1111726347931451,
    'log_gdp_o': 0.38956910821478136,
    'log_gdp_d': 0.8268301277848659,
    'log_distw': 0.39755587900955086}}},
 {'target': 'tradeflow_baci',
  'model_spec': 'MLP full',
  'data_version': 'lag0',
  'model_name': 'MLP_tradeflow_baci',
  'n_train': 3640,
  'n_test': 910,
  'rmse': 12.63247503299985,
  'mae': 5.371200332441091,
  'r2': -16.11477292202991,
  'shap importance (grouped)': {'exporter_FE': 1.3345178550050958,
   'importer_FE': 0.9271528433995019,
   'other': {'contig': 0.2862672430161284,
    'comlang_off': 0.38411440316167483,
    'comlang_ethno': 0.13950536072272404,
    'disorder_Demonstrations': 0.0229632477764624,
    'disorder_Political violence': 0.01528097608958887,
    'disorder_Political violence; Demonstrations': 0.07428361243986403,
    'disorder_Strategic developments': 0.02449734203929101,
    'event_Battles': 0.04159497092499571,
    'event_Explosions/Remote violence': 0.05934916225044188,
    'event_Protests': 0.10236306025784724,
    'event_Riots': 0.4813270684228174,
    'event_Strategic developments': 0.0916949425665375,
    'event_Violence against civilians': 0.3565199597346686,
    'perpetrator_Civilians': 0.003521311855141929,
    'perpetrator_External/Other forces': 0.024644423485195792,
    'perpetrator_Identity militia': 0.09269949148524238,
    'perpetrator_Political militia': 0.03400025820605143,
    'perpetrator_Protesters': 0.022603330766232638,
    'perpetrator_Rebel group': 0.1154276248290295,
    'perpetrator_Rioters': 0.17641908100672576,
    'perpetrator_State forces': 0.06915530166810846,
    'target_Civilians': 0.030780461896741464,
    'target_External/Other forces': 0.12170712521941533,
    'target_Identity militia': 0.04758672807441111,
    'target_Political militia': 0.13083425775703458,
    'target_Protesters': 0.039504928685164996,
    'target_Rebel group': 0.047562790628982804,
    'target_Rioters': 0.06700253125322035,
    'target_State forces': 0.14867593337813742,
    'log_gdp_o': 0.3918894381860678,
    'log_gdp_d': 1.2152296003481982,
    'log_distw': 0.381712405928879}}},
 {'target': 'tradeflow_baci',
  'model_spec': 'XGB basic',
  'data_version': 'lag0',
  'model_name': 'XGBoost_tradeflow_baci',
  'n_train': 3640,
  'n_test': 910,
  'rmse': 2.248696124591908,
  'mae': 1.629405909482402,
  'r2': 0.4576797925330913,
  'shap importance (grouped)': {'exporter_FE': 1.1000466,
   'importer_FE': 0.48996437,
   'other': {'contig': 0.41711366,
    'comlang_off': 0.058545556,
    'comlang_ethno': 0.026004603,
    'log_gdp_o': 0.8640532,
    'log_gdp_d': 0.5674534,
    'log_distw': 0.63089544}}},
 {'target': 'tradeflow_baci',
  'model_spec': 'XGB full',
  'data_version': 'lag0',
  'model_name': 'XGBoost_tradeflow_baci',
  'n_train': 3640,
  'n_test': 910,
  'rmse': 2.3778108685004953,
  'mae': 1.74401574110632,
  'r2': 0.39361442745670727,
  'shap importance (grouped)': {'exporter_FE': 0.74835795,
   'importer_FE': 0.5026265,
   'other': {'contig': 0.4014124,
    'comlang_off': 0.058334343,
    'comlang_ethno': 0.023343883,
    'disorder_Demonstrations': 0.06408133,
    'disorder_Political violence': 0.055403486,
    'disorder_Political violence; Demonstrations': 0.0132161,
    'disorder_Strategic developments': 0.034522418,
    'event_Battles': 0.05221999,
    'event_Explosions/Remote violence': 0.02726426,
    'event_Protests': 0.047266304,
    'event_Riots': 0.043777935,
    'event_Strategic developments': 0.0113256,
    'event_Violence against civilians': 0.04372717,
    'perpetrator_Civilians': 0.0004813217,
    'perpetrator_External/Other forces': 0.022466943,
    'perpetrator_Identity militia': 0.038238022,
    'perpetrator_Political militia': 0.078285605,
    'perpetrator_Protesters': 0.030691402,
    'perpetrator_Rebel group': 0.037447818,
    'perpetrator_Rioters': 0.024549231,
    'perpetrator_State forces': 0.06975314,
    'target_Civilians': 0.04290983,
    'target_External/Other forces': 0.03655358,
    'target_Identity militia': 0.027504481,
    'target_Political militia': 0.064246655,
    'target_Protesters': 0.008677454,
    'target_Rebel group': 0.016945057,
    'target_Rioters': 0.03125715,
    'target_State forces': 0.044453338,
    'log_gdp_o': 0.9764292,
    'log_gdp_d': 0.5447524,
    'log_distw': 0.6206511}}},
 {'target': 'tradeflow_comtrade_o',
  'model_spec': 'RF basic',
  'data_version': 'lag0',
  'model_name': 'RandomForest_tradeflow_comtrade_o',
  'n_train': 3640,
  'n_test': 910,
  'rmse': 1.9274115806045566,
  'mae': 1.3952320006000458,
  'r2': 0.47443790213118586,
  'shap importance (grouped)': {'exporter_FE': 1.081209488774185,
   'importer_FE': 0.3865783426255016,
   'other': {'contig': 0.3985036825583303,
    'comlang_off': 0.09060126993073386,
    'comlang_ethno': 0.04946369303781195,
    'log_gdp_o': 0.6412958518839729,
    'log_gdp_d': 0.47797264112930804,
    'log_distw': 0.5005014212324125}}},
 {'target': 'tradeflow_comtrade_o',
  'model_spec': 'RF full',
  'data_version': 'lag0',
  'model_name': 'RandomForest_tradeflow_comtrade_o',
  'n_train': 3640,
  'n_test': 910,
  'rmse': 2.10162738290778,
  'mae': 1.6094738669845696,
  'r2': 0.37513450128983883,
  'shap importance (grouped)': {'exporter_FE': 0.595355158559791,
   'importer_FE': 0.26028811849499905,
   'other': {'contig': 0.37665022469104287,
    'comlang_off': 0.0444530328281404,
    'comlang_ethno': 0.0298750449821933,
    'disorder_Demonstrations': 0.06176695250849021,
    'disorder_Political violence': 0.08758406701838405,
    'disorder_Political violence; Demonstrations': 0.018790540052670338,
    'disorder_Strategic developments': 0.021049892217455624,
    'event_Battles': 0.05692165324773686,
    'event_Explosions/Remote violence': 0.02127365022943414,
    'event_Protests': 0.08718278443897677,
    'event_Riots': 0.053209248343179,
    'event_Strategic developments': 0.02096436897445534,
    'event_Violence against civilians': 0.051947069705544156,
    'perpetrator_Civilians': 0.0013626181656173843,
    'perpetrator_External/Other forces': 0.0146144497072394,
    'perpetrator_Identity militia': 0.059996729101336535,
    'perpetrator_Political militia': 0.08778111760122657,
    'perpetrator_Protesters': 0.07270209898260596,
    'perpetrator_Rebel group': 0.02205328383316557,
    'perpetrator_Rioters': 0.06758083269293258,
    'perpetrator_State forces': 0.02748367667371777,
    'target_Civilians': 0.03963659397911242,
    'target_External/Other forces': 0.008581984261504246,
    'target_Identity militia': 0.03947284618636259,
    'target_Political militia': 0.025282347038504908,
    'target_Protesters': 0.02488565845844944,
    'target_Rebel group': 0.017970391418175427,
    'target_Rioters': 0.01995328324390897,
    'target_State forces': 0.03507901415994977,
    'log_gdp_o': 0.4252161286033871,
    'log_gdp_d': 0.4514630116790537,
    'log_distw': 0.4477654436738082}}},
 {'target': 'tradeflow_comtrade_o',
  'model_spec': 'MLP basic',
  'data_version': 'lag0',
  'model_name': 'MLP_tradeflow_comtrade_o',
  'n_train': 3640,
  'n_test': 910,
  'rmse': 2.001793119483314,
  'mae': 1.3975732315846348,
  'r2': 0.43309081459612253,
  'shap importance (grouped)': {'exporter_FE': 2.241802434310602,
   'importer_FE': 0.4729952510289044,
   'other': {'contig': 0.3728609304699415,
    'comlang_off': 0.04860449026604453,
    'comlang_ethno': 0.04357694961725281,
    'log_gdp_o': 0.8542764740965195,
    'log_gdp_d': 0.5426027296142316,
    'log_distw': 0.3789287185971294}}},
 {'target': 'tradeflow_comtrade_o',
  'model_spec': 'MLP full',
  'data_version': 'lag0',
  'model_name': 'MLP_tradeflow_comtrade_o',
  'n_train': 3640,
  'n_test': 910,
  'rmse': 10.883838024190176,
  'mae': 4.52925496952788,
  'r2': -15.758658421757278,
  'shap importance (grouped)': {'exporter_FE': 2.3275705302042593,
   'importer_FE': 0.44589685707186216,
   'other': {'contig': 0.24133374490570159,
    'comlang_off': 0.07068422519389195,
    'comlang_ethno': 0.022734256746900924,
    'disorder_Demonstrations': 0.09352036178823879,
    'disorder_Political violence': 0.009908732410656575,
    'disorder_Political violence; Demonstrations': 0.04451096468879876,
    'disorder_Strategic developments': 0.005535928528274886,
    'event_Battles': 0.025346040928975584,
    'event_Explosions/Remote violence': 0.05567796908313837,
    'event_Protests': 0.0007436083006696078,
    'event_Riots': 0.09200421478115474,
    'event_Strategic developments': 0.015164829095518428,
    'event_Violence against civilians': 0.22607463107450573,
    'perpetrator_Civilians': 0.003382730269347187,
    'perpetrator_External/Other forces': 0.01816159358683779,
    'perpetrator_Identity militia': 0.012369149306027902,
    'perpetrator_Political militia': 0.051845415536328626,
    'perpetrator_Protesters': 0.0026985547102685086,
    'perpetrator_Rebel group': 0.02052672522013842,
    'perpetrator_Rioters': 0.2894682928781346,
    'perpetrator_State forces': 0.1965187747054352,
    'target_Civilians': 0.1219931724460609,
    'target_External/Other forces': 0.045002834401436716,
    'target_Identity militia': 0.01740243822935439,
    'target_Political militia': 0.020488660812050957,
    'target_Protesters': 0.030104782806434603,
    'target_Rebel group': 0.2690980134511543,
    'target_Rioters': 0.04521675851690039,
    'target_State forces': 0.12355172753448594,
    'log_gdp_o': 0.9544069066642936,
    'log_gdp_d': 0.4881640267747589,
    'log_distw': 0.4252702479618518}}},
 {'target': 'tradeflow_comtrade_o',
  'model_spec': 'XGB basic',
  'data_version': 'lag0',
  'model_name': 'XGBoost_tradeflow_comtrade_o',
  'n_train': 3640,
  'n_test': 910,
  'rmse': 1.9344408713304964,
  'mae': 1.4163469417326804,
  'r2': 0.47059745056800184,
  'shap importance (grouped)': {'exporter_FE': 1.1817156,
   'importer_FE': 0.22783117,
   'other': {'contig': 0.40132627,
    'comlang_off': 0.08053067,
    'comlang_ethno': 0.030084332,
    'log_gdp_o': 0.77875936,
    'log_gdp_d': 0.6588386,
    'log_distw': 0.55740553}}},
 {'target': 'tradeflow_comtrade_o',
  'model_spec': 'XGB full',
  'data_version': 'lag0',
  'model_name': 'XGBoost_tradeflow_comtrade_o',
  'n_train': 3640,
  'n_test': 910,
  'rmse': 2.12434405605774,
  'mae': 1.5439671882546238,
  'r2': 0.3615530432448212,
  'shap importance (grouped)': {'exporter_FE': 0.8619643,
   'importer_FE': 0.24710253,
   'other': {'contig': 0.41379368,
    'comlang_off': 0.07149641,
    'comlang_ethno': 0.02475908,
    'disorder_Demonstrations': 0.060545627,
    'disorder_Political violence': 0.09586512,
    'disorder_Political violence; Demonstrations': 0.03434796,
    'disorder_Strategic developments': 0.038690522,
    'event_Battles': 0.06494036,
    'event_Explosions/Remote violence': 0.045246348,
    'event_Protests': 0.042555258,
    'event_Riots': 0.04307002,
    'event_Strategic developments': 0.007946613,
    'event_Violence against civilians': 0.067730196,
    'perpetrator_Civilians': 0.00022004919,
    'perpetrator_External/Other forces': 0.030976782,
    'perpetrator_Identity militia': 0.028595738,
    'perpetrator_Political militia': 0.07944926,
    'perpetrator_Protesters': 0.04271039,
    'perpetrator_Rebel group': 0.025755553,
    'perpetrator_Rioters': 0.04134899,
    'perpetrator_State forces': 0.049897473,
    'target_Civilians': 0.060781304,
    'target_External/Other forces': 0.0102742,
    'target_Identity militia': 0.028865162,
    'target_Political militia': 0.017617337,
    'target_Protesters': 0.019545443,
    'target_Rebel group': 0.022783265,
    'target_Rioters': 0.062054448,
    'target_State forces': 0.07262119,
    'log_gdp_o': 0.79269725,
    'log_gdp_d': 0.6082367,
    'log_distw': 0.5255255}}},
 {'target': 'tradeflow_comtrade_d',
  'model_spec': 'RF basic',
  'data_version': 'lag0',
  'model_name': 'RandomForest_tradeflow_comtrade_d',
  'n_train': 3640,
  'n_test': 910,
  'rmse': 2.1494108354822576,
  'mae': 1.5169496738436983,
  'r2': 0.4019364187529416,
  'shap importance (grouped)': {'exporter_FE': 1.2470115438504554,
   'importer_FE': 0.8383884361921399,
   'other': {'contig': 0.19855525283388056,
    'comlang_off': 0.056822114654699385,
    'comlang_ethno': 0.061645007809596655,
    'log_gdp_o': 0.8039976528915302,
    'log_gdp_d': 0.24093633287747507,
    'log_distw': 0.3331324558834127}}},
 {'target': 'tradeflow_comtrade_d',
  'model_spec': 'RF full',
  'data_version': 'lag0',
  'model_name': 'RandomForest_tradeflow_comtrade_d',
  'n_train': 3640,
  'n_test': 910,
  'rmse': 2.273793743388377,
  'mae': 1.7159306192668482,
  'r2': 0.330715721412176,
  'shap importance (grouped)': {'exporter_FE': 0.638055251026123,
   'importer_FE': 0.6816892605355341,
   'other': {'contig': 0.17767138004274863,
    'comlang_off': 0.04133360651104566,
    'comlang_ethno': 0.039828112160243116,
    'disorder_Demonstrations': 0.10952461704410821,
    'disorder_Political violence': 0.04953035464528688,
    'disorder_Political violence; Demonstrations': 0.013294702094807,
    'disorder_Strategic developments': 0.025769107458194416,
    'event_Battles': 0.0366108696965691,
    'event_Explosions/Remote violence': 0.014523857413121274,
    'event_Protests': 0.0909985106576639,
    'event_Riots': 0.06440008246469298,
    'event_Strategic developments': 0.03234807875837399,
    'event_Violence against civilians': 0.03308525611991328,
    'perpetrator_Civilians': 0.00015880425416561924,
    'perpetrator_External/Other forces': 0.03274033329791163,
    'perpetrator_Identity militia': 0.12747031893090102,
    'perpetrator_Political militia': 0.07326473220938606,
    'perpetrator_Protesters': 0.07837682358233858,
    'perpetrator_Rebel group': 0.029424516417015028,
    'perpetrator_Rioters': 0.039590585326712946,
    'perpetrator_State forces': 0.03636695303616257,
    'target_Civilians': 0.029544796936880235,
    'target_External/Other forces': 0.020092922431045438,
    'target_Identity militia': 0.04906440632666049,
    'target_Political militia': 0.024860198720407588,
    'target_Protesters': 0.04781799787596504,
    'target_Rebel group': 0.01855393155416602,
    'target_Rioters': 0.0315979139773803,
    'target_State forces': 0.03261253114312907,
    'log_gdp_o': 0.620523401478706,
    'log_gdp_d': 0.13264176663012908,
    'log_distw': 0.28384523369049813}}},
 {'target': 'tradeflow_comtrade_d',
  'model_spec': 'MLP basic',
  'data_version': 'lag0',
  'model_name': 'MLP_tradeflow_comtrade_d',
  'n_train': 3640,
  'n_test': 910,
  'rmse': 2.170585651937616,
  'mae': 1.4938292420659334,
  'r2': 0.39009478737827485,
  'shap importance (grouped)': {'exporter_FE': 1.287662377604525,
   'importer_FE': 1.6156707667760017,
   'other': {'contig': 0.19358994979103386,
    'comlang_off': 0.09898972216422942,
    'comlang_ethno': 0.07791841701052772,
    'log_gdp_o': 0.37154922433058285,
    'log_gdp_d': 1.185635758241828,
    'log_distw': 0.3070121460951037}}},
 {'target': 'tradeflow_comtrade_d',
  'model_spec': 'MLP full',
  'data_version': 'lag0',
  'model_name': 'MLP_tradeflow_comtrade_d',
  'n_train': 3640,
  'n_test': 910,
  'rmse': 8.516307696155103,
  'mae': 4.441627096671124,
  'r2': -8.388823562321528,
  'shap importance (grouped)': {'exporter_FE': 1.5123167565337106,
   'importer_FE': 1.7811347950620406,
   'other': {'contig': 0.11002663984128289,
    'comlang_off': 0.13234098491760007,
    'comlang_ethno': 0.07923634260379966,
    'disorder_Demonstrations': 0.12298721567265981,
    'disorder_Political violence': 0.022865130653234995,
    'disorder_Political violence; Demonstrations': 0.07900948403682234,
    'disorder_Strategic developments': 0.024232659082540315,
    'event_Battles': 0.1460276671582182,
    'event_Explosions/Remote violence': 0.024715864724655198,
    'event_Protests': 0.06578913303804505,
    'event_Riots': 0.23178371548304214,
    'event_Strategic developments': 0.03364744625283498,
    'event_Violence against civilians': 0.02514229573823254,
    'perpetrator_Civilians': 0.0026153359288609256,
    'perpetrator_External/Other forces': 0.04161586688637801,
    'perpetrator_Identity militia': 0.04848273766689559,
    'perpetrator_Political militia': 0.026125666244943446,
    'perpetrator_Protesters': 0.10131584523215435,
    'perpetrator_Rebel group': 0.028010111717030713,
    'perpetrator_Rioters': 0.039304136187774154,
    'perpetrator_State forces': 0.04460298330372538,
    'target_Civilians': 0.011050262604964433,
    'target_External/Other forces': 0.07048515921293746,
    'target_Identity militia': 0.06153801803024105,
    'target_Political militia': 0.166929644331063,
    'target_Protesters': 0.024107920226649475,
    'target_Rebel group': 0.010787245630817245,
    'target_Rioters': 0.04225049783023084,
    'target_State forces': 0.15414151229891074,
    'log_gdp_o': 0.3245635680947865,
    'log_gdp_d': 1.1612271136260814,
    'log_distw': 0.22969540088674903}}},
 {'target': 'tradeflow_comtrade_d',
  'model_spec': 'XGB basic',
  'data_version': 'lag0',

In [36]:
df = pd.DataFrame(results)
df[["model", "spec"]] = df["model_spec"].str.split(" ", expand=True)

In [37]:
df

,target,model_spec,data_version,model_name,n_train,n_test,rmse,mae,r2,shap importance (grouped),model,spec
0,tradeflow_baci,RF basic,lag0,RandomForest_tradeflow_baci,3640,910,2.196923,1.570715,0.482364,"{'exporter_FE': 1.0825656624986466, 'importer_...",RF,basic
1,tradeflow_baci,RF full,lag0,RandomForest_tradeflow_baci,3640,910,2.347838,1.771822,0.408805,"{'exporter_FE': 0.5906058946141746, 'importer_...",RF,full
2,tradeflow_baci,MLP basic,lag0,MLP_tradeflow_baci,3640,910,2.179484,1.634907,0.490550,"{'exporter_FE': 1.352158674525605, 'importer_F...",MLP,basic
3,tradeflow_baci,MLP full,lag0,MLP_tradeflow_baci,3640,910,12.632475,5.371200,-16.114773,"{'exporter_FE': 1.3345178550050958, 'importer_...",MLP,full
4,tradeflow_baci,XGB basic,lag0,XGBoost_tradeflow_baci,3640,910,2.248696,1.629406,0.457680,"{'exporter_FE': 1.1000466, 'importer_FE': 0.48...",XGB,basic
...,...,...,...,...,...,...,...,...,...,...,...,...
103,combined_trade_baci,RF full,lag2,RandomForest_combined_trade_baci,3276,910,1.639427,1.186319,0.542933,"{'exporter_FE': 0.3791631945410454, 'importer_...",RF,full
104,combined_trade_baci,MLP basic,lag2,MLP_combined_trade_baci,3276,910,1.591481,1.130970,0.569277,"{'exporter_FE': 0.9192257308366236, 'importer_...",MLP,basic
105,combined_trade_baci,MLP full,lag2,MLP_combined_trade_baci,3276,910,5.016347,3.091912,-3.279278,"{'exporter_FE': 0.8054708863387624, 'importer_...",MLP,full
106,combined_trade_baci,XGB basic,lag2,XGBoost_combined_trade_baci,3276,910,1.594707,1.107628,0.567529,"{'exporter_FE': 0.54252213, 'importer_FE': 0.5...",XGB,basic
107,combined_trade_baci,XGB full,lag2,XGBoost_combined_trade_baci,3276,910,1.648611,1.155659,0.537798,"{'exporter_FE': 0.40094975, 'importer_FE': 0.5...",XGB,full

In [38]:
df.sort_values("r2", ascending=False) \
  .groupby(["data_version", "target"]) \
  .head(1)[["data_version", "target", "model", "spec", "r2", "rmse"]]

    data_version                target model   spec        r2      rmse
102         lag2   combined_trade_baci    RF  basic  0.596609  1.540159
66          lag1   combined_trade_baci    RF  basic  0.592371  1.548574
30          lag0   combined_trade_baci    RF  basic  0.583010  1.566150
18          lag0       tradeflow_imf_o    RF  basic  0.506164  2.079399
54          lag1       tradeflow_imf_o    RF  basic  0.501465  2.088969
90          lag2       tradeflow_imf_o    RF  basic  0.492830  2.106715
2           lag0        tradeflow_baci   MLP  basic  0.490550  2.179484
74          lag2        tradeflow_baci   MLP  basic  0.489421  2.181782
36          lag1        tradeflow_baci    RF  basic  0.478799  2.204550
6           lag0  tradeflow_comtrade_o    RF  basic  0.474438  1.927412
78          lag2  tradeflow_comtrade_o    RF  basic  0.470902  1.932610
42          lag1  tradeflow_comtrade_o    RF  basic  0.469270  1.936226
100         lag2       tradeflow_imf_d   XGB  basic  0.435797  2.196026
86          lag2  tradeflow_comtrade_d   MLP  basic  0.434822  2.088814
28          lag0       tradeflow_imf_d   XGB  basic  0.422088  2.222523
60          lag1       tradeflow_imf_d    RF  basic  0.417636  2.231101
16          lag0  tradeflow_comtrade_d   XGB  basic  0.408702  2.137218
52          lag1  tradeflow_comtrade_d   XGB  basic  0.406880  2.140088

In [42]:
df[df["r2"] < 0][["data_version", "target", "model", "spec", "r2", "rmse"]]

    data_version                target model  spec         r2       rmse
3           lag0        tradeflow_baci   MLP  full -16.114773  12.632475
9           lag0  tradeflow_comtrade_o   MLP  full -15.758658  10.883838
15          lag0  tradeflow_comtrade_d   MLP  full  -8.388824   8.516308
21          lag0       tradeflow_imf_o   MLP  full -39.791952  18.898777
27          lag0       tradeflow_imf_d   MLP  full  -5.585960   7.502830
33          lag0   combined_trade_baci   MLP  full -37.803703  15.108004
39          lag1        tradeflow_baci   MLP  full  -2.245709   5.501383
45          lag1  tradeflow_comtrade_o   MLP  full  -6.419370   7.239404
51          lag1  tradeflow_comtrade_d   MLP  full  -2.384678   5.112330
57          lag1       tradeflow_imf_o   MLP  full  -3.634321   6.369087
63          lag1       tradeflow_imf_d   MLP  full  -1.874012   4.956397
69          lag1   combined_trade_baci   MLP  full  -7.868231   7.223004
75          lag2        tradeflow_baci   MLP  full  -1.896270   5.196364
81          lag2  tradeflow_comtrade_o   MLP  full  -2.421642   4.914660
87          lag2  tradeflow_comtrade_d   MLP  full  -2.215859   4.982598
93          lag2       tradeflow_imf_o   MLP  full  -1.562998   4.735909
99          lag2       tradeflow_imf_d   MLP  full  -1.055524   4.191612
105         lag2   combined_trade_baci   MLP  full  -3.279278   5.016347

In [40]:
pivot = df.pivot_table(
    index=["data_version", "target", "model"],
    columns="spec",
    values="r2"
)

pivot["gain_full_vs_basic"] = pivot["full"] - pivot["basic"]

In [41]:
pivot

spec                                        basic       full  \
data_version target               model
lag0         combined_trade_baci  MLP    0.578084 -37.803703
                                  RF     0.583010   0.504907
                                  XGB    0.538384   0.511214
             tradeflow_baci       MLP    0.490550 -16.114773
                                  RF     0.482364   0.408805
                                  XGB    0.457680   0.393614
             tradeflow_comtrade_d MLP    0.390095  -8.388824
                                  RF     0.401936   0.330716
                                  XGB    0.408702   0.387649
             tradeflow_comtrade_o MLP    0.433091 -15.758658
                                  RF     0.474438   0.375135
                                  XGB    0.470597   0.361553
             tradeflow_imf_d      MLP    0.390011  -5.585960
                                  RF     0.418554   0.324126
                                  XGB    0.422088   0.372310
             tradeflow_imf_o      MLP    0.408346 -39.791952
                                  RF     0.506164   0.395427
                                  XGB    0.490285   0.424648
lag1         combined_trade_baci  MLP    0.552656  -7.868231
                                  RF     0.592371   0.549592
                                  XGB    0.551306   0.539300
             tradeflow_baci       MLP    0.466705  -2.245709
                                  RF     0.478799   0.453059
                                  XGB    0.464905   0.448422
             tradeflow_comtrade_d MLP    0.392139  -2.384678
                                  RF     0.393451   0.370334
                                  XGB    0.406880   0.393631
             tradeflow_comtrade_o MLP    0.445549  -6.419370
                                  RF     0.469270   0.394063
                                  XGB    0.454143   0.450782
             tradeflow_imf_d      MLP    0.354408  -1.874012
                                  RF     0.417636   0.396411
                                  XGB    0.416707   0.410892
             tradeflow_imf_o      MLP    0.363036  -3.634321
                                  RF     0.501465   0.465258
                                  XGB    0.485147   0.484916
lag2         combined_trade_baci  MLP    0.569277  -3.279278
                                  RF     0.596609   0.542933
                                  XGB    0.567529   0.537798
             tradeflow_baci       MLP    0.489421  -1.896270
                                  RF     0.470506   0.419169
                                  XGB    0.468329   0.425391
             tradeflow_comtrade_d MLP    0.434822  -2.215859
                                  RF     0.405429   0.366226
                                  XGB    0.406169   0.388852
             tradeflow_comtrade_o MLP    0.444757  -2.421642
                                  RF     0.470902   0.412220
                                  XGB    0.461871   0.436728
             tradeflow_imf_d      MLP    0.363979  -1.055524
                                  RF     0.421711   0.373490
                                  XGB    0.435797   0.369680
             tradeflow_imf_o      MLP    0.379778  -1.562998
                                  RF     0.492830   0.453689
                                  XGB    0.479879   0.440943

spec                                     gain_full_vs_basic
data_version target               model
lag0         combined_trade_baci  MLP            -38.381786
                                  RF              -0.078103
                                  XGB             -0.027170
             tradeflow_baci       MLP            -16.605323
                                  RF              -0.073559
                                  XGB             -0.064065
             tradeflow_comtrade_d MLP             -8.778918
                                  RF              -0.071221
                                  XGB             -0.021053
             tradeflow_comtrade_o MLP            -16.191749
                                  RF              -0.099303
                                  XGB             -0.109044
             tradeflow_imf_d      MLP             -5.975970
                                  RF              -0.094428
                                  XGB             -0.049778
             tradeflow_imf_o      MLP            -40.200298
                                  RF              -0.110737
                                  XGB             -0.065637
lag1         combined_trade_baci  MLP             -8.420888
                                  RF              -0.042778
                                  XGB             -0.012006
             tradeflow_baci       MLP             -2.712414
                                  RF              -0.025739
                                  XGB             -0.016483
             tradeflow_comtrade_d MLP             -2.776816
                                  RF              -0.023118
                                  XGB             -0.013249
             tradeflow_comtrade_o MLP             -6.864919
                                  RF              -0.075207
                                  XGB             -0.003361
             tradeflow_imf_d      MLP             -2.228421
                                  RF              -0.021224
                                  XGB             -0.005815
             tradeflow_imf_o      MLP             -3.997357
                                  RF              -0.036207
                                  XGB             -0.000231
lag2         combined_trade_baci  MLP             -3.848554
                                  RF              -0.053676
                                  XGB             -0.029730
             tradeflow_baci       MLP             -2.385691
                                  RF              -0.051337
                                  XGB             -0.042938
             tradeflow_comtrade_d MLP             -2.650681
                                  RF              -0.039203
                                  XGB             -0.017317
             tradeflow_comtrade_o MLP             -2.866399
                                  RF              -0.058682
                                  XGB             -0.025143
             tradeflow_imf_d      MLP             -1.419503
                                  RF              -0.048221
                                  XGB             -0.066117
             tradeflow_imf_o      MLP             -1.942775
                                  RF              -0.039141
                                  XGB             -0.038936

In [43]:
def flatten_shap(shap_dict):
    flat = {}
    for k, v in shap_dict.items():
        if isinstance(v, dict):
            for sub_k, sub_v in v.items():
                flat[f"{k}_{sub_k}"] = float(sub_v)
        else:
            flat[k] = float(v)
    return flat

clean = []
for r in results:
    base = {k: v for k, v in r.items() if k != "shap importance (grouped)"}
    base.update(flatten_shap(r["shap importance (grouped)"]))
    clean.append(base)

df = pd.DataFrame(clean)

In [ ]:
df.columns = df.columns.str.replace("^other_", "", regex=True)
df.to_csv("results/clean_shap_results.csv", index=False)

In [52]:
df

,target,model_spec,data_version,model_name,n_train,n_test,rmse,mae,r2,exporter_FE,...,perpetrator_Rioters,perpetrator_State forces,target_Civilians,target_External/Other forces,target_Identity militia,target_Political militia,target_Protesters,target_Rebel group,target_Rioters,target_State forces
0,tradeflow_baci,RF basic,lag0,RandomForest_tradeflow_baci,3640,910,2.196923,1.570715,0.482364,1.082566,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tradeflow_baci,RF full,lag0,RandomForest_tradeflow_baci,3640,910,2.347838,1.771822,0.408805,0.590606,...,0.041316,0.044154,0.032814,0.024855,0.051438,0.027322,0.020011,0.021321,0.020749,0.031437
2,tradeflow_baci,MLP basic,lag0,MLP_tradeflow_baci,3640,910,2.179484,1.634907,0.490550,1.352159,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,tradeflow_baci,MLP full,lag0,MLP_tradeflow_baci,3640,910,12.632475,5.371200,-16.114773,1.334518,...,0.176419,0.069155,0.030780,0.121707,0.047587,0.130834,0.039505,0.047563,0.067003,0.148676
4,tradeflow_baci,XGB basic,lag0,XGBoost_tradeflow_baci,3640,910,2.248696,1.629406,0.457680,1.100047,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,combined_trade_baci,RF full,lag2,RandomForest_combined_trade_baci,3276,910,1.639427,1.186319,0.542933,0.379163,...,0.027929,0.021419,0.023630,0.007062,0.026212,0.015602,0.023101,0.014722,0.010852,0.023351
104,combined_trade_baci,MLP basic,lag2,MLP_combined_trade_baci,3276,910,1.591481,1.130970,0.569277,0.919226,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,combined_trade_baci,MLP full,lag2,MLP_combined_trade_baci,3276,910,5.016347,3.091912,-3.279278,0.805471,...,0.081049,0.084081,0.130330,0.050478,0.048266,0.037807,0.006965,0.024971,0.084320,0.105239
106,combined_trade_baci,XGB basic,lag2,XGBoost_combined_trade_baci,3276,910,1.594707,1.107628,0.567529,0.542522,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,combined_trade_baci,XGB full,lag2,XGBoost_combined_trade_baci,3276,910,1.648611,1.155659,0.537798,0.400950,...,0.037800,0.042038,0.033587,0.011895,0.011435,0.014313,0.010816,0.013084,0.013368,0.048724

In [47]:
df.groupby(["data_version", "model_name", "model_spec"])[
    ["other_log_gdp_o", "other_log_gdp_d"]
].mean()

                                                      other_log_gdp_o  \
data_version model_name                   model_spec
lag0         MLP_combined_trade_baci      MLP basic          0.670725
                                          MLP full           0.406571
             MLP_tradeflow_baci           MLP basic          0.389569
                                          MLP full           0.391889
             MLP_tradeflow_comtrade_d     MLP basic          0.371549
...                                                               ...
lag2         XGBoost_tradeflow_comtrade_o XGB full           0.726626
             XGBoost_tradeflow_imf_d      XGB basic          0.905358
                                          XGB full           0.999254
             XGBoost_tradeflow_imf_o      XGB basic          0.925419
                                          XGB full           0.958232

                                                      other_log_gdp_d
data_version model_name                   model_spec
lag0         MLP_combined_trade_baci      MLP basic          0.552173
                                          MLP full           0.778606
             MLP_tradeflow_baci           MLP basic          0.826830
                                          MLP full           1.215230
             MLP_tradeflow_comtrade_d     MLP basic          1.185636
...                                                               ...
lag2         XGBoost_tradeflow_comtrade_o XGB full           0.625343
             XGBoost_tradeflow_imf_d      XGB basic          0.414626
                                          XGB full           0.346113
             XGBoost_tradeflow_imf_o      XGB basic          0.570763
                                          XGB full           0.511560

[108 rows x 2 columns]

In [63]:
df_filtered = df[(df["event_Riots"] > 0.1) & (df["model_spec"] != "MLP full")]

In [70]:
event_cols = df.columns[df.columns.str.startswith("disorder_")]

df_filtered = df[
    (df[event_cols].gt(0.1).any(axis=1)) &
    (df["model_spec"] != "MLP full")
]

In [71]:
df_filtered

,target,model_spec,data_version,model_name,n_train,n_test,rmse,mae,r2,exporter_FE,...,perpetrator_Rioters,perpetrator_State forces,target_Civilians,target_External/Other forces,target_Identity militia,target_Political militia,target_Protesters,target_Rebel group,target_Rioters,target_State forces
13,tradeflow_comtrade_d,RF full,lag0,RandomForest_tradeflow_comtrade_d,3640,910,2.273794,1.715931,0.330716,0.638055,...,0.039591,0.036367,0.029545,0.020093,0.049064,0.024860,0.047818,0.018554,0.031598,0.032613
47,tradeflow_comtrade_o,XGB full,lag1,XGBoost_tradeflow_comtrade_o,3458,910,1.969662,1.434321,0.450782,0.873813,...,0.050041,0.058144,0.031238,0.010955,0.029218,0.028960,0.009277,0.014139,0.043586,0.041297
55,tradeflow_imf_o,RF full,lag1,RandomForest_tradeflow_imf_o,3458,910,2.163496,1.602917,0.465258,0.718728,...,0.066597,0.030562,0.066453,0.009683,0.042244,0.021105,0.017160,0.027873,0.023098,0.034100
59,tradeflow_imf_o,XGB full,lag1,XGBoost_tradeflow_imf_o,3458,910,2.123358,1.528293,0.484916,0.965352,...,0.014556,0.068738,0.026946,0.014198,0.013673,0.016737,0.012281,0.025119,0.013866,0.032181
91,tradeflow_imf_o,RF full,lag2,RandomForest_tradeflow_imf_o,3276,910,2.186498,1.667785,0.453689,0.670995,...,0.077621,0.027566,0.045670,0.012134,0.040529,0.028316,0.027675,0.027464,0.019896,0.032755